version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tickr-slack-bot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1p1xh0o7t4y31"
s3_prefix = "tickr-slack-bot"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

