AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Gratapi

  Sample SAM Template for Gratapi

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: python3.7
    Timeout: 180
    MemorySize: 128
    Environment:
      Variables:
        PATH: "/var/task/bin/"
        PYTHONPATH: "/var/task/src:/var/task/lib"

Resources:
  GratapiWrite:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: handler_write.handle
      Runtime: python3.7
      Events:
        Write:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /write
            Method: POST

  GratApiCognitoAuth:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: handler_auth.handle
      Runtime: python3.7
      Policies:
        - AmazonCognitoPowerUser
      Events:
        Write:
          Type: Api
          Properties:
            Path: /auth
            Method: POST

Outputs:
  GratpiWriteApi:
    Description: "API Gateway endpoint URL for Prod stage for Gratapi"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/write/"
  GratapiWrite:
    Description: "Gratapi Lambda Function ARN"
    Value: !GetAtt GratapiWrite.Arn
  GratapiWriteIamRole:
    Description: "Implicit IAM Role created for Gratapi"
    Value: !GetAtt GratapiWrite.Arn
