AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Gratapi

  Sample SAM Template for Gratapi

Parameters:
    UserPoolId:
      Type: String
      Description: Userpool ID
      Default: userpoolid
    AppClientId:
      Type: String
      Default: appclientid
    AppClientSecret:
      Type: String
      Default: appclientsecret

Globals:
  Function:
    Runtime: python3.7
    Timeout: 180
    MemorySize: 128
    Environment:
      Variables:
        PATH: "/var/task/bin/"
        PYTHONPATH: "/var/task/src:/var/task/lib"
        USER_POOL_ID: !Ref UserPoolId
        APP_CLIENT_ID: !Ref AppClientId
        APP_CLIENT_SECRET: !Ref AppClientSecret

Resources:

  GratitudesTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: "gratitudes"
      AttributeDefinitions: 
        - 
          AttributeName: "email"
          AttributeType: "S"
        - 
          AttributeName: "day"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "email"
          KeyType: "HASH"
        - 
          AttributeName: "day"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  Gratapi:
    Type: AWS::Serverless::Api
    Properties:
      Name: GratApi
      StageName: test
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: "arn:aws:cognito-idp:eu-west-1:645571371616:userpool/eu-west-1_omQ17WWBq"

  GratapiWrite:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: handler_write.handle
      Runtime: python3.7
      Policies:
        # Make this a statement for write access to specific resource
        - AmazonDynamoDBFullAccess
      Events:
        Write:
          Type: Api
          Properties:
            Path: /write
            RestApiId: !Ref Gratapi
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

  GratApiCognitoAuth:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: handler_auth.handle
      Runtime: python3.7
      Policies:
        - AmazonCognitoPowerUser
      Events:
        Write:
          Type: Api
          Properties:
            Path: /auth
            RestApiId: !Ref Gratapi
            Method: POST
