AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  tickrbot

  Sample SAM Template for tickrbot

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: python3.8
    Timeout: 180
    MemorySize: 128
    Environment:
      Variables:
        PATH: "/var/task/bin/"
        PYTHONPATH: "/var/task/src:/var/task/lib"

Resources:
  SlackbotWebhook:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: handler_webhook.handle
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /incoming
            Method: POST

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Slack Webook"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/incoming/"
  SlackbotWebhook:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt SlackbotWebhook.Arn
  SlackbotWebhookIamRole:
    Description: "Implicit IAM Role created for Slack Webook"
    Value: !GetAtt SlackbotWebhookRole.Arn
